server:
  port: 8087
spring:
  application:
    name: check-domain #指定服务名
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试邮箱配置
  #邮件发送配置
  mail:
    host: smtpdm.aliyun.com
    username: ${MailUsername}
    password: ${MailPassword}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#设置一个邮件发送人
customize:
  mail:
    sender: ${MailUsername}
    receive: ${MailReceiver}
  query:
    password: ${QueryKey}
#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug