server:
  port: 8087
spring:
  application:
    name: check-domain #指定服务名
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试邮箱配置
  mvc:
    async:
      request-timeout: 5000 #接口请求超时时间设置
  #邮件发送配置
  mail:
    #邮件服务地址
    host: smtpdm.aliyun.com
    #用户名
    username: ${MailUsername}
    #密码
    password: ${MailPassword}
    #编码格式
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        smtp:
          #如果用ssl方式，需要配置以下属性
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
#设置一个邮件发送人
customize:
  mail:
    senderName: 域名注册监控Api
    sender: ${MailUsername}
  query:
    password: ${QueryKey}
#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug